### ISSUE TITLE
如何获取应用菜单事件？

### ISSUE THREAD

**Issue by shuaiyy** [xen0n/go-workwx#105]
回调后端有收到消息，callback handler `OnIncomingMessage`没有解析到event message；
 EventKey是应用菜单里用户自定义的值

能否提供debug的思路
还有扩展解析workwx.RxMessage新类型的方法

**Comment by xen0n** [comment]
checkout 本库的一份本地副本，在你项目的 `go.mod` 里 `replace` 出来，`fmt.Printf` 到地老天荒即可

关于添加新的 `RxMessage` 类型，可参考 #102 里 rx 相关文件的改动

**Comment by xen0n** [comment]
消息类型的处理在 `extractMessageExtras` 函数（自己找）

**Comment by shuaiyy** [comment]
感谢大佬；

看起来缺失了很多事件类型；
企业自建App里的这些都没有 

[事件格式](https://developer.work.weixin.qq.com/document/path/90240)

我fork一个改一下试试

> 消息类型的处理在 `extractMessageExtras` 函数（自己找）

**Comment by xen0n** [comment]
> 感谢大佬；
> 
> 看起来缺失了很多事件类型； 企业自建App里的这些都没有
> 
> [事件格式](https://developer.work.weixin.qq.com/document/path/90240)
> 
> 我fork一个改一下试试
> 
> > 消息类型的处理在 `extractMessageExtras` 函数（自己找）

Feel free to!

如同已经在很多地方解释过的那样，很长一段时间内七牛都没有推送消息之外的其他需求，我近几年的业余时间也不写业务，所以用起来有缺失的地方自己加上就好了。提交增加上游 API 覆盖的 PR 我会很快看的。十分感谢！
