### ISSUE TITLE
单个go项目，多个企微自建应用分开发送消息，会出现access_token missing 错误

### ISSUE THREAD

**Issue by dafa168** [xen0n/go-workwx#116]
暂无问题

**Comment by xen0n** [comment]
编辑历史不会消失 :joy:

所以前面的问题，它还是不是个问题？已解决的话自助 close

**Comment by xen0n** [comment]
> 表里存了很多个自建应用参数，每次要发消息，都先从库里拿一条自建应用的参数，new wxapp() , 然后再获取token， 然后去发消息， 但是会碰到 access_token missing的错误。

可以发一下简化过的你的业务代码吗？感觉像是使用姿势不对（这可能意味着我要做些变更以适应这种姿势，不一定意味着你就想错了）。

只需要包含 `workwx.New`、`WithApp`、`SpawnAccessTokenRefresher` 和发消息的调用，及其周围有必要保留的最少代码即可。

**Comment by xen0n** [comment]
另外，我看到你在 #73 自荐帮忙维护了（当时因为我没有看到你有显著的开源项目贡献，也没有给本项目的贡献历史，因此无视了）。现在可以确定你有在活跃使用本项目，也有一些沟通能力，因此如果你有想法改动这边的东西（加功能、修看到的问题、帮忙把陈年 issue 重新过一遍之类的），直接提 PR 就好了。

**Comment by dafa168** [comment]
好的，谢谢老哥，简化代码如下  :

```
	wk := &biz.WeWork{}
	if err := r.data.msgdb.WithContext(ctx).Model(&biz.WeWork{}).First(wk).Error; err != nil {
		return err
	}
	
	client := workwx.New(wk.CorpId)
	app := client.WithApp(wk.Secret, wk.AgentId)
	// preferably do this at app initialization
	app.SpawnAccessTokenRefresherWithContext(ctx)
	
	// send to user(s)
	to1 := workwx.Recipient{
		UserIDs: qwUsers,
	}

	// 发送文本消息
	if err = app.SendTextMessage(&to1, "消息内容", false); err != nil {
		return err
	}
```

**Comment by xen0n** [comment]
这是每次发消息都从 workwx.New 开始初始化一套新的客户端实例吗？

本项目的预期使用姿势是全局单例，可以理解为每个 `(corpid, secret, agentid)` 的组合（对应 App）都只应该被构造一次，在这个前提下，不太可能出问题。

可以看看能不能用一个池子缓存住所有的 apps 实例，每次拿着 `(corpid, secret, agentid)` 去 get，应该就没事了

**Comment by dafa168** [comment]
嗯嗯，我试试看。

**Comment by dafa168** [comment]
![image](https://user-images.githubusercontent.com/2015166/196683002-e20e7f95-a9bf-45f5-a631-57835263bc8c.png)
老哥， 大概改成这样了。帮忙看下哈，谢谢。

**Comment by xen0n** [comment]
> ![image](https://user-images.githubusercontent.com/2015166/196683002-e20e7f95-a9bf-45f5-a631-57835263bc8c.png)
> 老哥， 大概改成这样了，帮忙看下哈 。
> 下面这个刷新token，放外面不确定有没有问题，请老哥指教下，谢谢。

spawn refresher 时候传入的 ctx 仅仅用来方便控制在确定时机停止这个刷新 goroutine，大部分时候不适用于短请求的情况。这个 goroutine 一般在 WithApp 之后马上起来。

**Comment by xen0n** [comment]
> 嗯嗯，那就是只用执行一次就好了吧

对的，每个app只需要配套执行一次这个

**Comment by dafa168** [comment]
好的，感谢老哥。此问题已解决。
