### ISSUE TITLE
backoff包升级带来的问题

### ISSUE THREAD

**Issue by rudy-tao** [xen0n/go-workwx#129]
github.com/cenkalti/backoff/v4 v4.2.0 用的是go的1.18版本，里面用到了泛型。

我这边项目用的go版本是1.17，直接引用最新版的go-workwx是会报错的。

我看go-workwx用的也是1.17。

想问下 升级mod到4.2.0是因为什么呢？

**Comment by rudy-tao** [comment]
@xen0n

**Comment by xen0n** [comment]
> 想问下 升级mod到4.2.0是因为什么呢？

无脑升上去的，出问题是因为 `cenkalti/backoff` 没有遵守 semver 的规范，在 minor version bump 里做了不兼容改动。

马上修一下

**Comment by xen0n** [comment]
另外感谢您报告此事，使我知道野外有这个库的使用者没升到 go1.18（我本来有 bump `go.mod` 最低支持版本的想法了），这样我可能晚一些做 `v2` 的不兼容升级。（虽然升了也不影响你用，但以我目前的业余时间分配，出了 v2 大概率 v1 就不会再有更新了，等于去除了你们场景的支持）

**Comment by xen0n** [comment]
Filed upstream issue https://github.com/cenkalti/backoff/issues/128.

**Comment by xen0n** [comment]
[Released v1.3.1](https://github.com/xen0n/go-workwx/releases/tag/v1.3.1).

不好意思！

**Comment by bo-er** [comment]
Please don't use Chinese on github.
