### ISSUE TITLE
素材上传报错44001

### ISSUE THREAD

**Issue by liqinshan** [xen0n/go-workwx#155]
调用UploadTempFileMedia()接口上传素材，一直报44001的错误，empty media data。

```go
	mediaFile, err := workwx.NewMediaFromFile(f)
	if err != nil {
		return
	}
	
	mediaUploadResp, err := client.UploadTempFileMedia(mediaFile)
	if err != nil {
		return
	}
```

**Comment by xen0n** [comment]
目前看不出问题，方便提供下 `f` 的细节吗？

**Comment by liqinshan** [comment]
自己实现了一段逻辑，也是报同样的错误。打印了原始http请求，没看到和企业微信官方文档有啥区别。

```go
	info, err := f.Stat()
	if err != nil {
		logging.GetLogger().Errorf("获取file属性失败, err: %v", err)
		return RespMediaUpload{}, errors.Wrap(err, "获取file属性失败")
	}

	// 1. 读取文件内容
	bodyBuf := &bytes.Buffer{}
	bodyWriter := multipart.NewWriter(bodyBuf)

	h := make(textproto.MIMEHeader)
	h.Set("Content-Disposition",
		fmt.Sprintf(`form-data; name="media";filename="%s"; filelength=%d`, filepath.Base(f.Name()), info.Size()))
	h.Set("Content-Type", "application/octet-stream")

	fileWriter, err := bodyWriter.CreatePart(h)
	if err != nil {
		logging.GetLogger().Errorf("写入buffer失败, err: %v", err)
		return RespMediaUpload{}, errors.Wrap(err, "写入buffer失败")
	}

	_, err = io.Copy(fileWriter, f)
	if err != nil {
		return RespMediaUpload{}, errors.Wrap(err, "copy失败")
	}

	err = bodyWriter.Close()
	if err != nil {
		return RespMediaUpload{}, errors.Wrap(err, "body writer关闭失败")
	}

	// 2. 上传文件
	urlStr := w.opts.QYAPIHost + fmt.Sprintf("/cgi-bin/media/upload?access_token=%s&type=%s", w.accessToken.getToken(), "file")
	req, err := http.NewRequest("POST", urlStr, bodyBuf)
	if err != nil {
		return RespMediaUpload{}, errors.Wrap(err, "创建http req失败")
	}

	// 2.1 设置header
	req.Header.Set("Content-Type", bodyWriter.FormDataContentType())

	// 打印req请求，调试用
	reqDump, err := httputil.DumpRequest(req, true)
	if err == nil {
		fmt.Println(string(reqDump))
	}

	// 3. 执行请求
	resp, err := w.opts.HTTP.Do(req)
	if err != nil {
		logging.GetLogger().Errorf("执行企业微信上传素材接口失败, err: %v", err)
		return RespMediaUpload{}, errors.Wrap(err, "执行企业微信上传素材接口失败")
	}

	defer func() {
		_ = resp.Body.Close()
	}()

	var result RespMediaUpload
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		logging.GetLogger().Errorf("企业微信上传素材接口返回值解析失败, err: %v", err)
		return RespMediaUpload{}, errors.Wrap(err, "企业微信上传素材接口返回值解析失败")
	}
	return result, nil
```

**Comment by liqinshan** [comment]
> 自己实现了一段逻辑，也是报同样的错误。打印了原始http请求，没看到和企业微信官方文档有啥区别。
> 
> ```go
> 	info, err := f.Stat()
> 	if err != nil {
> 		logging.GetLogger().Errorf("获取file属性失败, err: %v", err)
> 		return RespMediaUpload{}, errors.Wrap(err, "获取file属性失败")
> 	}
> 
> 	// 1. 读取文件内容
> 	bodyBuf := &bytes.Buffer{}
> 	bodyWriter := multipart.NewWriter(bodyBuf)
> 
> 	h := make(textproto.MIMEHeader)
> 	h.Set("Content-Disposition",
> 		fmt.Sprintf(`form-data; name="media";filename="%s"; filelength=%d`, filepath.Base(f.Name()), info.Size()))
> 	h.Set("Content-Type", "application/octet-stream")
> 
> 	fileWriter, err := bodyWriter.CreatePart(h)
> 	if err != nil {
> 		logging.GetLogger().Errorf("写入buffer失败, err: %v", err)
> 		return RespMediaUpload{}, errors.Wrap(err, "写入buffer失败")
> 	}
> 
> 	_, err = io.Copy(fileWriter, f)
> 	if err != nil {
> 		return RespMediaUpload{}, errors.Wrap(err, "copy失败")
> 	}
> 
> 	err = bodyWriter.Close()
> 	if err != nil {
> 		return RespMediaUpload{}, errors.Wrap(err, "body writer关闭失败")
> 	}
> 
> 	// 2. 上传文件
> 	urlStr := w.opts.QYAPIHost + fmt.Sprintf("/cgi-bin/media/upload?access_token=%s&type=%s", w.accessToken.getToken(), "file")
> 	req, err := http.NewRequest("POST", urlStr, bodyBuf)
> 	if err != nil {
> 		return RespMediaUpload{}, errors.Wrap(err, "创建http req失败")
> 	}
> 
> 	// 2.1 设置header
> 	req.Header.Set("Content-Type", bodyWriter.FormDataContentType())
> 
> 	// 打印req请求，调试用
> 	reqDump, err := httputil.DumpRequest(req, true)
> 	if err == nil {
> 		fmt.Println(string(reqDump))
> 	}
> 
> 	// 3. 执行请求
> 	resp, err := w.opts.HTTP.Do(req)
> 	if err != nil {
> 		logging.GetLogger().Errorf("执行企业微信上传素材接口失败, err: %v", err)
> 		return RespMediaUpload{}, errors.Wrap(err, "执行企业微信上传素材接口失败")
> 	}
> 
> 	defer func() {
> 		_ = resp.Body.Close()
> 	}()
> 
> 	var result RespMediaUpload
> 	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
> 		logging.GetLogger().Errorf("企业微信上传素材接口返回值解析失败, err: %v", err)
> 		return RespMediaUpload{}, errors.Wrap(err, "企业微信上传素材接口返回值解析失败")
> 	}
> 	return result, nil
> ```

原始请求的打印结果如下：
![image](https://github.com/xen0n/go-workwx/assets/4413442/0e8ac739-f14f-4721-908d-a229ff2635ba)

**Comment by xen0n** [comment]
你自己拼的这个原始请求，看 multipart 那俩分隔行中间的部分是上传文件内容，就是空的。。。。

建议围绕 `f` 排查，你的逻辑和库都不背锅

**Comment by liqinshan** [comment]
> 你自己拼的这个原始请求，看 multipart 那俩分隔行中间的部分是上传文件内容，就是空的。。。。
> 
> 建议围绕 `f` 排查，你的逻辑和库都不背锅

谢谢，我按照这个思路排查下试试。

**Comment by xen0n** [comment]
> > > 你自己拼的这个原始请求，看 multipart 那俩分隔行中间的部分是上传文件内容，就是空的。。。。
> > > 建议围绕 `f` 排查，你的逻辑和库都不背锅
> > 
> > 
> > 谢谢，我按照这个思路排查下试试。
> 
> 经过排查，确实是f的锅。*os.File对象提前被Cose掉了，读取到的内容为空。

感谢及时反馈！论 RAII 写法在 Go 中仍然具备的战略价值和 `defer` 的意义 ;-)
