### ISSUE TITLE
企业微信群机器人功能

### ISSUE THREAD

**Issue by ipfans** [xen0n/go-workwx#16]
希望可以支持企业微信群机器人功能

**Comment by xen0n** [comment]
你说得有道理，可以做个独立模块

**Comment by xen0n** [comment]
我看看十一结束前能不能做出来（十一有很多现实生活的事情要做，不能全部写代码）

**Comment by xen0n** [comment]
Implementation note:

* 跟正常发消息貌似一样，可以复用入口
* 鉴权方式不是 access token 而是单独一个 bot key
* 请求格式是 `${QYAPI_HOST}/cgi-bin/webhook/send?key=${BOT_KEY}` 这样

**Comment by jinfagang** [comment]
@xen0n 老铁机器人微信群功能开发的咋样了

**Comment by xen0n** [comment]
之前公司方面没需求，我自己这两年业余时间都在搞底层，不过上个月公司项目要用群机器人了（感谢疼讯，appchat 接口不能 at 人，mmd）因此做了简单的 1.1.0 版本，请大家试用。

这个天坑终于（一部分）填掉了。。
