### ISSUE TITLE
想用 redis/其他存储 来实现多个 pod 共用一个 accesstoken

### ISSUE THREAD

**Issue by sunznx** [xen0n/go-workwx#197]
感觉目前的代码实现起来比较麻烦。目前想到的实现是：
1. 要么把这个锁做成 interface
<img width="463" alt="image" src="https://github.com/xen0n/go-workwx/assets/8629792/3b752328-1f3d-4b1b-afcc-e81f5bc88099">

2. 要么这个 getAccessToken 暴露成公有方法
<img width="836" alt="image" src="https://github.com/xen0n/go-workwx/assets/8629792/0ea1fd92-0889-4ee5-9049-75ba2f9aed5e">

**Comment by yoogoc** [comment]
自己实现一个`ITokenProvider`应该可以满足你的需求
