### ISSUE TITLE
为何go get -u 会报错

### ISSUE THREAD

**Issue by xlzeng** [xen0n/go-workwx#22]
go: gopkg.in/urfave/cli.v2@v2.1.1: go.mod has non-....v2 module path "github.com/urfave/cli/v2" at revision v2.1.1

**Comment by xen0n** [comment]
`go version` 输出？
`go env` 输出？

**Comment by xen0n** [comment]
ping

**Comment by xen0n** [comment]
啊，这块应该已经 fixed in commit 372d15b9879caa1611786373ecaf2ebb9d4de9e5
