### ISSUE TITLE
SendTextCardMessage resp 疑问

### ISSUE THREAD

**Issue by loktarjugg** [xen0n/go-workwx#32]
建议优化下sendMessage的resp返回，目前是忽略的。在某些情况下会导致开发者无法获悉消息是否已经成功发出。比如：超出消息发送频率限制

**Comment by xen0n** [comment]
Got it，可能一周到一个月内做

**Comment by xen0n** [comment]
咦，目前应该处理掉了。。升到最新版本再看一下？

https://github.com/xen0n/go-workwx/blob/1573e72ca4e27a6700133fe247e6fb94a5084662/message.go#L224-L232

https://github.com/xen0n/go-workwx/blob/1573e72ca4e27a6700133fe247e6fb94a5084662/apis.md.go#L96-L98

https://github.com/xen0n/go-workwx/blob/1573e72ca4e27a6700133fe247e6fb94a5084662/models.go#L40-L49

`message.go` 最后的 `TODO` 应该要去掉的，忘了。。。

**Comment by xen0n** [comment]
我大概知道了，没发版= =

因为接收消息这一部分的文档还没写，写完之前我不想发（否则因为是第一个支持接收消息的版本，人们就会升上来，然后我再发估计大家也不会跟着升级了），所以不介意的话，要不先依赖一下 `develop` 分支看看能不能用？

**Comment by loktarjugg** [comment]
好的，感谢回复。
我用下develop分支试试
