### ISSUE TITLE
send message to workwx response no error, but message did not deliver 

### ISSUE THREAD

**Issue by waterzh** [xen0n/go-workwx#64]
in message.go

func (c *WorkwxApp) sendMessage(
	recipient *Recipient,
	msgtype string,
	content map[string]interface{},
	isSafe bool,
) error {
//...

if err != nil {
		return err
	}

        //return errmsg it not succeed
	if resp.ErrCode != 0 {
		return fmt.Errorf("errcode:%d, errmsg:%s", resp.ErrCode, resp.ErrMsg)
	}
	return nil

}

**Comment by xen0n** [comment]
Needs more context. Also your message is malformated, I can't seem to understand it nor find any actionable suggestion.

**Comment by xen0n** [comment]
Ideally provide a minimal example that reproduces the bug, with the secrets replaced with placeholder values, so I can verify myself with my own credentials.

**Comment by waterzh** [comment]
就是resp返回码需要检查一下, 如果resp.ErrorCode 不等于0, 需要返回出错, 而不是nil.  
我的场景是access_token失效时发送消息时发现的.

**Comment by xen0n** [comment]
This logic is already existing, `sendMessage` invokes `execMessageSend` or `execAppchatSend`, both of which include `resp.TryIntoErr()` attempts that do exactly what you describe. So it should be impossible to have `ErrCode != 0` while `err == nil`...

**Comment by waterzh** [comment]
Get it.
the whole store for the issue :

 I need to deploy the service in serveral IDC, to send message to the same app in enterprise wechat(workwx), so I have to share access token between these IDCs.  

my solution  (change accesstoken.go):  
on the main IDC to get access token from workwx, save in database, 
other (slave) IDCs read it from database and cache it in memory.
only the main idc can update the access token from workwx. 

something wrong in the access_token sharing, so even send mesage to wechat failed (cause by access token failed), i got no error.  this is whole story.

so for mutlple IDCs to use this library,  do you hava and plan or idea to support it. 
As tencent have officially suggestted to share access_token.

**Comment by waterzh** [comment]
thanks a lot for sharing.

**Comment by xen0n** [comment]
Got it, the crux is allowing clients to retrieve tokens from some external mechanism. This could be trivially solved with a provider pattern.

I'll update the code in maybe a week or so, would that be OK for you?

**Comment by waterzh** [comment]
OK. thanks.
