### ISSUE TITLE
如何自助保活goroutine

### ISSUE THREAD

**Issue by ocavue** [xen0n/go-workwx#67]
我在[文档](https://pkg.go.dev/github.com/xen0n/go-workwx@v1.0.0-alpha.2#:~:text=自助保活)中发现了多个标记「该 goroutine 本身没有 keep-alive 逻辑，需要自助保活」的 API。请问对于这样的 API，应当如何进行自助保活呢？希望可以有更具体的解释。如果可以有代码片段的话就更好了。谢谢。

**Comment by xen0n** [comment]
Hi,

“保活”指的是不要让 main goroutine 提前退出，而导致进程提前退出。对于多数永远不结束的 Web 后端服务而言，什么都不需要做；如果您的场景下有必要使 main goroutine 活得更久一些，该怎么做怎么做就可以了。

**Comment by ocavue** [comment]
@xen0n 谢谢你的解答
