### ISSUE TITLE
大佬，我调用 "SendTextMessage" 一直报 48002 怎么回事呢？

### ISSUE THREAD

**Issue by orestonce** [xen0n/go-workwx#69]

**Comment by xen0n** [comment]
请提供更多信息，如复现问题所需的代码片段（去掉敏感信息），你的企业微信后台配置情况等等

另外 48002 在官方文档有常见问题和排查步骤，也请先确认下不是踩了常见坑

**Comment by orestonce** [comment]
![截屏2021-06-15 3.15.29.png](https://i.loli.net/2021/06/15/7OjCzrkUHDxcAwK.png)

**Comment by orestonce** [comment]
发现了，是secret key没复制完整。-_-
