### ISSUE TITLE
用户id 从哪里来的。

### ISSUE THREAD

**Issue by wxf4150** [xen0n/go-workwx#7]
// send to user(s)
	to1 := workwx.Recipient{
		UserIDs: []string{"testuser"},
	}

testuser 这个词 从哪里来的。用户id是要从企业微信的用户列表里取得的，go-workwx目前应该还没有这样的接口

**Comment by wxf4150** [comment]
用户id 群id 部门id 都无法 获得， 怎么发送消息啊？

**Comment by xen0n** [comment]
我们公司的 use case，用户 ID 就是这个人的 LDAP ID，已经有了。。群是事先创建好的，ID 也是知道的 :joy:

最近一阵都很忙（你可以看到我 profile 多少 private contributions :new_moon_with_face:），不过既然有人反馈了，那就找个时间实现一下~

**Comment by qinhf3-L** [comment]
现在获取部门成员详情接口已经实现了。可以结合部门列表接口来获取用户详情。

**Comment by rocklau** [comment]
其实就建一个机器人群就可以了。然后把人拉进去。

**Comment by xen0n** [comment]
这个还是看具体需求，一般都是对某个部门，或者某个群进行操作，拉出成员列表、发消息之类。

**Comment by xen0n** [comment]
重新看了下已实现的接口，目前部门成员列表、获取群信息的 API 都实现了。

这个问题可以认为解决了，closing
