### ISSUE TITLE
文档驱动代码生成！

### ISSUE THREAD

**Issue by xen0n** [xen0n/go-workwx#9]
markdown 文档 -> `go generate` -> `gopkg.in/russross/blackfriday.v2` -> 代码

**Comment by xen0n** [comment]
实现了 model 的生成，接下来要做 API 接口（调用 `executeQYAPIGet` `executeQYAPIPost` 方法的方法）的自动生成

**Comment by dfang** [comment]
为什么要文档生成模型呢？
麻烦呀 官方更新文档了 你这边也要更新文档，还不如直接链接到官网api页面

嫌模型字段太多 可以  json to go 啊
https://transform.now.sh/json-to-go/

**Comment by xen0n** [comment]
你说得有道理，我在开发过程中也发现了这一点。

文档驱动是我的实验方向之一，因为反正都要写一大堆东西（目前的项目结构一点也不 Go，因为那一阵子我们团队被 Go 一些语言 feature 坑得死去活来，我故意组织得很像 Rust 看看能走多远），以后也不一定只用来生成 Go 一种语言的 SDK。比方说，我自己的业余项目都是 Rust 的，其中也有需要用到企业微信 SDK 的时候，我不想写两次胶水代码。总之有很多个人原因。

JSON to Go 或者其他的方式，最后都是致力于减少维护工作量这一点。这个点完全可以讨论，我 open to suggestions。

**Comment by xen0n** [comment]
* `json-to-go` 根本没有降低人的工作量（我当时还以为是自动同步更新模型呢）
* 目前的 `sdkcodegen` 暂且满足了多数需求，手写的代码降到了可以维护的程度，虽然 `req` `resp` 类型的自动生成还是个值得考虑的点

closing
