### ISSUE TITLE
发企微消息提示： access_token missing

### ISSUE THREAD

**Issue by dafa168** [xen0n/go-workwx#97]
老哥，麻烦看下这个问题哈，采用自建应用发企微消息，过几天就自动出现： Code: 41001, Msg: "access_token missing， 这个提示了。 
当前有三个自建应用，都是不同的企业，都是在http请求到了之后，在实例化weworkApp ，然后调用的 
```golang
client := workwx.New(wk.CorpId)
app := client.WithApp(wk.Secret, wk.AgentId)
app.SpawnAccessTokenRefresherWithContext(ctx)

//下面开始发消息，
```
这样会有问题么？ 麻烦老哥看到了，帮忙看下哈

**Comment by dafa168** [comment]
已经找到答案了，老哥很久以前就回复了。 弄好之后，并且经过这几天观察，没问题了。
请看 ： https://github.com/xen0n/go-workwx/issues/67

**Comment by xen0n** [comment]
> 已经找到答案了，老哥很久以前就回复了。 弄好之后，并且经过这几天观察，没问题了。
> 请看 ： https://github.com/xen0n/go-workwx/issues/67

哦哦，那我明白了，你之前的写法大概率是用了个会结束的 context，因为正常 access token 刷新 goroutine 不会自己结束。。
